# matches.py — Shared match data for the WC2026 ticket tracker

MATCHES = [
    {
        "Match #": 5,
        "Fixture": "Haiti vs Scotland",
        "Date": "Sat, Jun 13 2026",
        "Time": "9:00 PM ET",
        "Venue": "Boston Stadium",
        "Venue Map": "https://www.stadiumsportus.com/stadiums/gillette-stadium/seating-map",
        "Stage": "Group Stage",
        "Category": "Cat 2",
        "Seats": "Block 224, Row 6, Seats 7–10",
        "Tier": "Middle Tier",
        "# Tickets": 4,
        "Face Value / Ticket": 400.00,
        "url": "https://seatdata.io/events/haiti-vs-scotland-world-cup-group-c-foxborough-jun-13-2026/1126436/",
    },
    {
        "Match #": 30,
        "Fixture": "Scotland vs Morocco",
        "Date": "Fri, Jun 19 2026",
        "Time": "6:00 PM ET",
        "Venue": "Boston Stadium",
        "Venue Map": "https://www.stadiumsportus.com/stadiums/gillette-stadium/seating-map",
        "Stage": "Group Stage",
        "Category": "Cat 1",
        "Seats": "Block 137, Row 2, Seats 7–10",
        "Tier": "Lower Tier",
        "# Tickets": 4,
        "Face Value / Ticket": 600.00,
        "url": "https://seatdata.io/events/scotland-vs-morocco-world-cup-group-c-foxborough-jun-19-2026/1126446/",
    },
    {
        "Match #": 42,
        "Fixture": "France vs Iraq",
        "Date": "Mon, Jun 22 2026",
        "Time": "5:00 PM ET",
        "Venue": "Philadelphia Stadium",
        "Venue Map": "https://www.stadiumsportus.com/stadiums/lincoln-financial-field/seating-map?map=23",
        "Stage": "Group Stage",
        "Category": "Cat 2",
        "Seats": "Block 225, Row 27, Seats 17–20",
        "Tier": "Upper Tier",
        "# Tickets": 4,
        "Face Value / Ticket": 430.00,
        "url": "https://seatdata.io/events/france-vs-tbd-world-cup-group-i-philadelphia-jun-22-2026/1126440/",
    },
    {
        "Match #": 68,
        "Fixture": "Croatia vs Ghana",
        "Date": "Sat, Jun 27 2026",
        "Time": "5:00 PM ET",
        "Venue": "Philadelphia Stadium",
        "Venue Map": "https://www.stadiumsportus.com/stadiums/lincoln-financial-field/seating-map?map=23",
        "Stage": "Group Stage",
        "Category": "Cat 1",
        "Seats": "Block 131, Row 19, Seats 9–12",
        "Tier": "Lower Tier",
        "# Tickets": 4,
        "Face Value / Ticket": 500.00,
        "url": "https://seatdata.io/events/croatia-vs-ghana-world-cup-group-l-philadelphia-jun-27-2026/1126430/",
    },
    {
        "Match #": 74,
        "Fixture": "1E vs 3A/B/C/D/F",
        "Date": "Mon, Jun 29 2026",
        "Time": "4:30 PM ET",
        "Venue": "Boston Stadium",
        "Venue Map": "https://www.stadiumsportus.com/stadiums/gillette-stadium/seating-map",
        "Stage": "Round of 32",
        "Category": "Cat 1",
        "Seats": "Block 141, Row 24, Seats 13–16",
        "Tier": "Lower Tier",
        "# Tickets": 4,
        "Face Value / Ticket": 620.00,
        "url": "https://seatdata.io/events/1e-vs-3abcdf-world-cup-round-of-32-foxborough-jun-29-2026/1126437/",
    },
    {
        "Match #": 89,
        "Fixture": "Winner M74 vs Winner M77",
        "Date": "Sat, Jul 04 2026",
        "Time": "5:00 PM ET",
        "Venue": "Philadelphia Stadium",
        "Venue Map": "https://www.stadiumsportus.com/stadiums/lincoln-financial-field/seating-map?map=23",
        "Stage": "Round of 16",
        "Category": "Cat 1",
        "Seats": "Block 107, Row 13, Seats 13–16",
        "Tier": "Lower Tier",
        "# Tickets": 4,
        "Face Value / Ticket": 840.00,
        "url": "https://seatdata.io/events/w74-vs-w77-world-cup-round-of-16-philadelphia-jul-04-2026/1126431/",
    },
    {
        "Match #": 97,
        "Fixture": "Winner M89 vs Winner M90",
        "Date": "Thu, Jul 09 2026",
        "Time": "4:00 PM ET",
        "Venue": "Boston Stadium",
        "Venue Map": "https://www.stadiumsportus.com/stadiums/gillette-stadium/seating-map",
        "Stage": "Quarter-Final",
        "Category": "Cat 2",
        "Seats": "Block 334, Row 13, Seats 21–24",
        "Tier": "Upper Tier",
        "# Tickets": 4,
        "Face Value / Ticket": 890.00,
        "url": "https://seatdata.io/events/w89-vs-w90-world-cup-quarter-finals-foxborough-jul-09-2026/1126456/",
    },
]

FALLBACKS = {
    5:  {"get_in": 485,  "median": 1200, "change": 6.4,  "demand": "🟡 Moderate"},
    30: {"get_in": 550,  "median": 1469, "change": 4.4,  "demand": "🔴 Low"},
    42: {"get_in": 463,  "median": 1000, "change": 0.3,  "demand": "🟡 Moderate"},
    68: {"get_in": 466,  "median": 1334, "change": 30.3, "demand": "🔴 Low"},
    74: {"get_in": 539,  "median": 1768, "change": 0.5,  "demand": "🔴 Low"},
    89: {"get_in": 816,  "median": 2500, "change": 13.0, "demand": "🔴 Low"},
    97: {"get_in": 1127, "median": 2787, "change": 0.0,  "demand": "🔴 Low"},
}

TIER_TO_SECTION = {
    "Lower Tier": "Lower Bowl",
    "Upper Tier": "Upper Bowl",
    "Middle Tier": "Club Level",
}
